@startuml Denuncia_Web
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** vía Web

actor Denunciante as pre
collections Web
actor Supervisor as sup
actor Operador_SSP as opssp
collections SSP 


pre -> Web : ingresa
pre -> Web : selecciona denuncia en línea
pre -> Web : llena formulario
Web->sup: envía correo
sup->opssp:asigna caso
opssp->pre:comunicación con denunciante
opssp->pre:concertar reunión
pre->opssp:reunión con operario
opssp -> pre : solicita información
pre->opssp:relacion de hecho
opssp->pre:orientacion de hecho
opssp->SSP:registra caso
SSP->opssp: entrega formulario de registro
opssp->pre:entrega formulario impreso para firma
pre->opssp:entrega formulario firmado







@enduml