@startuml Denuncia_Whatsapp
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** vía Whatsapp

actor Presentante as pre
collections Whatsapp
entity Defensa as def
actor Supervisor as sup
actor Operador_SSP as opssp
collections SSP 


pre -> Whatsapp : envía mensaje inicial
Whatsapp -> def : notifica
def -> Whatsapp : solicita información
Whatsapp->pre: notifica
pre -> Whatsapp : envía información solicitada
Whatsapp->def: notifica
def-> Whatsapp: envia caso
Whatsapp->sup: notifica
sup->opssp:asigna caso
opssp->pre:comunicación con presentante
opssp->pre:concertar reunión
pre->opssp:reunión con operario
opssp -> pre : solicita informacion
pre->opssp:relacion de hecho
opssp->pre:orientacion de hecho
opssp->SSP:registra caso
SSP->opssp: entrega formulario de registro
opssp->pre:entrega formulario impreso para firma
pre->opssp:entrega formulario firmado



@enduml