@startuml Denuncia_Linea_Gratuita
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** vía Línea_Gratuita

actor Presentante as pre
collections Línea_Gratuita
entity Defensa as def
collections Whatsapp as wap
actor Supervisor as sup
actor Operador_SSP as opssp
collections SSP

pre -> Línea_Gratuita : llama
Línea_Gratuita -> def : comunica
def -> pre : solicita información
pre -> def : envía información solicitada
def->wap : envía caso
wap->sup : notifica
sup->wap : asigna caso
wap->opssp : notifica
opssp->pre:comunicación con presentante
opssp->pre:concertar reunión
pre->opssp:reunión con operario
opssp -> pre : solicita información
pre->opssp:relacion de hecho
opssp->pre:orientacion de hecho
opssp->SSP:registra caso
SSP->opssp: entrega formulario de registro
opssp->pre:entrega formulario impreso para firma
pre->opssp:entrega formulario firmado


@enduml