@startuml Diagrama_Sistema
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Sistema SSP

actor Operador_SSP as opssp
collections SSP
actor Supervisor_SSP as supssp
actor Delegado_o_Coordinador as delcor

opssp->SSP: crear caso
opssp->SSP: registro del denunciante
note over opssp, SSP: Se puede registrar, modificar y eliminar \n en cualquiermomento antes de la conclusion del caso
opssp->SSP: registro de institución 
note over opssp, SSP: Se puede registrar, modificar y eliminar \n en cualquiermomento antes de la conclusion del caso
opssp->SSP: registro de archivo
note over opssp, SSP: Se puede registrar, modificar y eliminar \n en cualquiermomento antes de la conclusion del caso
opssp->SSP: registro de derecho vulnerado
note over opssp, SSP: Se puede registrar, modificar y eliminar \n en cualquiermomento antes de la conclusion del caso
opssp->SSP: registro de grupo vulnerable
note over opssp, SSP: Se puede registrar, modificar y eliminar \n en cualquiermomento antes de la conclusion del caso
opssp->SSP: selección de tipo de proceso
opssp->opssp: realiza acciones defensoriales
opssp->SSP: registro de acciones defensoriales
opssp->SSP: solitud de conclusión del caso
SSP->supssp: notifica
supssp->SSP: validación de conclusión del caso
supssp->SSP: solicitud de archivo del caso
SSP->delcor: notifica
delcor->SSP: validación de archivo del caso

@enduml