@startuml Denuncia_Oficinas
skinparam Style strictuml
skinparam SequenceMessageAlignment center
mainframe **Denuncia** en Oficinas

actor Presentante as per
actor Operador_SSP as opssp

per -> opssp : reune
opssp -> per : solicita informacion

@enduml