@startuml Denuncia_web
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** vía web

actor Presentante as pre
collections Pagina_web as web
actor Operador_SSP as opssp
collections SSP 
collections API_SEGIP as segip

pre -> web : ingresa
pre -> web : selecciona denuncia en línea
pre -> web : llena formulario
web -> segip : envia de datos
segip -> web : validación 
segip-> web: informacion
web->SSP : crea pre-registro
SSP->web : notifica
web->pre : presenta indicaciones
SSP->opssp : notifica
opssp->SSP : busca pre-registro
SSP->opssp : presenta información
opssp->pre : concertar reunión
pre->opssp: reunión con operario
opssp->SSP : busca pre-registro
SSP->opssp : presenta información
opssp -> pre : solicita información complementaria
pre->opssp : relación de hecho
opssp->SSP : registra caso
opssp->pre : orientación
SSP->opssp : entrega formulario de registro
opssp->pre : entrega formulario impreso para firma
pre->opssp : entrega formulario firmado

@enduml