@startuml Denuncia_Escrita
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** Escrita

actor Presentante as pre
entity Defensoría as def
actor Supervisor as sup
actor Operador_SSP as opssp
collections API_SEGIP as segip
collections SSP 


pre -> def: escribe carta
def->sup:envía información de presentante
sup->opssp : designa
opssp->pre:comunicación con presentante
opssp->pre:concertar reunión
pre->opssp:reunión con operario
opssp -> pre : solicita informacion
pre->opssp:relacion de hecho
opssp->pre:orientación
opssp -> segip : envia de datos
segip -> opssp : validación 
opssp->SSP:registra caso
SSP->opssp: entrega formulario de registro
opssp->pre:entrega formulario impreso para firma
pre->opssp:entrega formulario firmado

@enduml