@startuml Denuncia_Escrita
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** Escrita

actor Presentante as pre
entity Defensoría as def
actor Supervisor as sup
actor Operador_SSP as opssp
collections SSP
collections API_SEGIP as segip

pre -> def : escribe carta
def->sup :envía caso
sup->opssp : designa
opssp->pre : comunicación con presentante
opssp->pre : concertar reunión
pre->opssp : reunión con operario
opssp -> pre : solicita informacion
pre->opssp : relación de hecho
opssp->SSP : registra caso
SSP -> segip : envia datos
segip -> SSP : validación
segip -> SSP : información
SSP->opssp : entrega formulario de registro
opssp->pre : orientación
opssp->pre : entrega formulario impreso para firma
pre->opssp : entrega formulario firmado

@enduml