@startuml Denuncia_Oficinas
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** en Oficinas

actor Denunciante as pre
actor Operador_SSP as opssp
collections SSP 
collections API_SEGIP as segip

pre -> opssp : reunion con operario
opssp -> pre : solicita información
pre -> opssp : relación del hecho
opssp -> SSP : registra caso
SSP -> segip : envia datos
segip -> SSP : validación 
segip -> SSP : información 
SSP->opssp: entrega formulario de registro
opssp -> pre : orientación
opssp->pre: entrega formulario impreso para firma
pre->opssp: entrega formulario firmado

@enduml