@startuml Diagrama_Sistema
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Sistema con Constitucional

actor Operador_SSP as opssp
collections SSP
actor Supervisor_SSP as supssp
actor Supervisor_Constitucional as supconsti
actor Operador_Constitucional as opconsti
collections API_SEGIP as segip
collections AGETIC as agetic

opssp->SSP: ingresa
opssp->SSP: selecciona crear caso
opssp->SSP: llena formulario
SSP->segip: envia informacion
segip->SSP: validacion
segip->SSP: información
SSP->SSP: registra caso
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado 
SSP->opssp: notifica
opssp->SSP: selecciona tipo de proceso
opssp->SSP: registra el proceso
opssp->SSP: seleciona acciones defensoriales
opssp->SSP: registra acciones defensoriales
opssp->SSP: selecciona enviar a consulta constitucional
SSP->supssp: notifica
supssp->SSP: seleciona caso
supssp->SSP: valida
SSP->supconsti: notifica
supconsti->SSP: seleciona caso
supconsti->SSP: valida
supconsti->SSP: designa operador constitucional
SSP->opconsti: notifica
opconsti->opconsti: procesa
opconsti->SSP: selecciona caso
opconsti->SSP: registra acciones constitucional
opconsti->SSP: envia caso
SSP->supconsti: notifica
supconsti->SSP: seleciona caso
supconsti->SSP: valida
SSP->opssp: notifica
opssp->SSP: selecciona conclusión de caso
SSP->supssp: muestra casos para conclusión
supssp->SSP: selecciona caso
SSP->supssp: muestra caso
supssp->SSP: validad
SSP->SSP: registra conclusión
SSP->opssp: notifica
opssp->SSP: seleciona formulario de conclusión
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado
SSP->opssp: notifica

@enduml