@startuml Diagrama_Sistema
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Sistema con Constitucional y Pre-registro

actor Operador_SSP as opssp
collections SSP
actor Supervisor_SSP as supssp
actor Supervisor_Constitucional as supconsti
actor Operador_Constitucional as opconsti
collections AGETIC as agetic

opssp->SSP: ingresa
opssp->SSP: busca pre registros
opssp->SSP: selecciona caso
opssp->SSP: llena formulario
SSP->SSP: registra caso
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado 
SSP->opssp: notifica
opssp->SSP: selecciona tipo de proceso
opssp->SSP: registra el proceso
opssp->SSP: seleciona acciones defensoriales
opssp->SSP: registra acciones defensoriales
opssp->SSP: selecciona enviar a consulta constitucional
SSP->supconsti: notifica
supconsti->SSP: seleciona caso
supconsti->SSP: valida
supconsti->SSP: designa operador constitucional
SSP->opconsti: notifica
opconsti->opconsti: procesa
opconsti->SSP: selecciona caso
opconsti->SSP: envia acciones constitucional
SSP->opssp: notifica
opssp->SSP: selecciona acciones constitucional
opssp->SSP: registra acciones constitucional
opssp->SSP: selcciona conclusión de caso
SSP->supssp: muestra casos para conclusión
supssp->SSP: selecciona caso
SSP->supssp: muestra caso
supssp->SSP: validad
SSP->SSP: registra conclusión
SSP->opssp: notifica
opssp->SSP: seleciona formulario de conclusión
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado
SSP->opssp: notifica

@enduml