@startuml Diagrama_Sistema
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Sistema con Resolución Defensorial

actor Operador_SSP as opssp
collections SSP
actor Supervisor_SSP as supssp
actor Delegado_SSP as del
collections API_SEGIP as segip
collections AGETIC as agetic

opssp->SSP: ingresa
opssp->SSP: selecciona crear caso
opssp->SSP: llena formulario
SSP->segip: envia informacion
segip->SSP: validacion
segip->SSP: información
SSP->SSP: registra caso
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado 
SSP->opssp: notifica
opssp->SSP: selecciona tipo de proceso
opssp->SSP: registra el proceso
opssp->SSP: seleciona acciones defensoriales
opssp->SSP: registra acciones defensoriales
opssp->SSP: selecciona enviar a resolución defensorial
SSP->del: notifica
del->SSP: seleciona caso
del->SSP: valida
del->del: procesa resolución defensorial
del->SSP: envia resolución defensorial
del->SSP: designa operador
SSP->opssp: notifica
opssp->opssp: procesa
opssp->SSP: selecciona caso
opssp->SSP: seguimiento a resolución defensorial
opssp->SSP: registra seguimiento a resolución defensorial
opssp->SSP: selcciona conclusión de caso
SSP->supssp: muestra casos para conclusión
supssp->SSP: selecciona caso
SSP->supssp: muestra caso
supssp->SSP: validad
SSP->SSP: registra conclusión
SSP->opssp: notifica
opssp->SSP: seleciona formulario de conclusión
SSP->agetic: envia formulario para su firma digital
agetic->SSP: formulario firmado
SSP->opssp: notifica

@enduml