@startuml Denuncia_web
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Denuncia** vía web

actor Supervisor_SSP as supssp
collections SSP 
actor Operador_SSP as opssp

supssp -> SSP : ingresa
supssp -> SSP : busca caso
supssp -> SSP : designa nuevo operario
SSP -> opssp : notifica

@enduml