@startuml Denuncia_web
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Reasignación entre Delegaciones o Coordinaciones

actor Supervisor_SSP as supssp
collections SSP 
actor Supervisor_Delegacion as supsspdel
actor Operador_SSP as opssp

supssp -> SSP : ingresa
supssp -> SSP : busca caso
supssp -> SSP : envia caso
SSP -> supsspdel : notifica
supsspdel -> SSP : acepta
supsspdel -> SSP : asigna
SSP -> opssp : notifica

@enduml