@startuml Registrar_Grupo
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Registro de Grupo

actor Administrador_Sistema as admin
collections SSP 

admin -> SSP : ingresa
admin -> SSP : crear grupo
admin -> SSP : codigo del grupo
admin -> SSP : nombre del grupo
SSP -> SSP : registra
SSP -> admin : notifica 

@enduml