@startuml Dashboard de Reportes
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Reportes Sistema SSP

actor Operador_SSP as opssp
collections SSP 
collections APIs_Defensoria as apidef

opssp -> SSP : ingresa
opssp -> SSP : selecciona dashboard
SSP -> apidef : solicta información
apidef -> SSP : envia información
SSP -> opssp : presenta la información
opssp -> SSP : seleciona exportar
SSP -> opssp : entrega reportes

@enduml