@startuml Registrar_Forma
skinparam Style strictuml
skinparam SequenceMessageAlignment center

mainframe **Diagrama** Registro de Forma de Conclusión

actor Administrador_Sistema as admin
collections SSP 

admin -> SSP : ingresa
admin -> SSP : crear forma de conclusión
admin -> SSP : código del grupo
admin -> SSP : nombre del grupo
SSP -> SSP : registra
SSP -> admin : notifica 

@enduml