@startuml flujo_del_sistema
start
:Denuncia;
split
  :Oficinas;
  :Atención del caso|
split again
  :Otros medios;
  :Pre registro;
end split
:Registro de caso;
-> Seleccion del Tipo proceso;
split
  :Investigación;
  :Acciones Defensoriales;
  if (Se requieren Acciones Especializadas) then (Si)
    if (Es un proceso constitucional) then (Si)
      :Registro;
      :Procesamiento del Caso|
      :Acciones constitucionales;
    else (No)
      :Procesamiento del Caso|
      :Resolución Defensorial;
      :Seguimiento de Resolución Defensorial;
    endif
  else (No)
  endif
split again
  :Orientación;
  :Atención|
  :Registro;
split again
  :Gestión;
  :Atención|
  :Registro;
split again
  :Rechazo;
  :Atención|
  :Registro;
end split
:Solicitud de Conclusión del Caso;
:Conclusión del Caso;
end
@enduml
